### ISSUE TITLE
Replace Write-Host with Write-Verbose on function execution.

### ISSUE THREAD

**Issue by cadayton** [PureStorage-OpenConnect/flashblade-powershell-toolkit#1]
I created a branch with the fixes, but was denied committing the branch.

This fix allows the caller to decide whether the generated output is desired by including the -verbose option on the function call.

Write-Host ("Running function: {0} " -f $MyInvocation.MyCommand);
Write-Host '---------------------------------------------------';

TO

Write-Verbose ("Running function: {0} " -f $MyInvocation.MyCommand);
Write-Verbose '---------------------------------------------------';

**Comment by kiwistorageguy** [comment]
Craig, I cant see your branch for some reason. I do have an updated version that only shows the module name if debug is on. If I updated the master with this version, would you like to try that?

**Comment by cadayton** [comment]
Hi Alex,
Sure I can clone your updated version.

When I attempted push my branch, it gave a permission error.  So makes sense you couldn't see my branch.

Thanks.

Craig Dayton
cadayton@protonmail.com
360-466-8778
paypal.me/CraigDayton

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
