### ISSUE TITLE
PureFBModule not loading from PSModulePath

### ISSUE THREAD

**Issue by cadayton** [PureStorage-OpenConnect/flashblade-powershell-toolkit#2]
Copied files to PSModulePath location
...\PureFBModule\1.0\

Upon start up of a PowerShell 7 session, 'Get-Module -ListAvailable' is not showing PureFBModule loaded.

The module can be loaded directly into a shell session window by using the 'Import-Module' command.  I'm not sure about the exact cause at this time.

**Comment by kiwistorageguy** [comment]
Try removing the 1.0 from the path name. I am running PowerShell 6 and do not need it.
